### ISSUE TITLE
Add torrent via Magnet

### ISSUE THREAD

**Issue by sachaw** [TypeCtrl/qbittorrent#49]
I am using this library in conjunction with an RSS parser, as many RSS feeds, use magnets instead of links to torrent files, I require this functionality, after searching the codebase, the only reference I found is the "magnet_uri" property of the torrent interface, is there an easy way to implement this, I don't mind digging around and submitting a pr.

**Comment by scttcper** [comment]
i got you bud

**Comment by sachaw** [comment]
Legend, God dam you make interacting with torrent clients easy.
